Repository google/xls, pull requests merged in 2020-10, with the labels that each got.

#151 Fixes for python3.9 and gcc-10.2.1
  dependency_support/com_github_grpc_grpc/BUILD
  dependency_support/com_github_grpc_grpc/grpc-cython.patch
  dependency_support/initialize_external.bzl
  dependency_support/load_external.bzl
  dependency_support/pip_requirements.txt
Labels: Reviewing Internally, build, cla: yes

#155 Fix typo in README.md install instructions
  README.md
Labels: cla: yes, documentation

#158 Add a top-level gitignore
  .gitignore
Labels: cla: yes

#147 Specialize select arms
  xls/ir/node.h
  xls/passes/BUILD
  xls/passes/post_dominator_analysis.h
  xls/passes/select_simplification_pass.cc
  xls/passes/select_simplification_pass_test.cc
Labels: Reviewing Internally, cla: yes

#148 Use html checkbox checked state on initial draw
  xls/visualization/ir_viz/templates/splash.tmpl
Labels: Reviewing Internally, cla: yes, enhancement, visualization

#171 Eliminate the need for "the container hack".
  .gitignore
  dependency_support/pybind11/pybind11.bzl
  xls/ir/BUILD
  xls/ir/container_hack.inc
  xls/ir/container_hack_undef.inc
  xls/ir/node.h
  xls/ir/package.cc
  xls/ir/package.h
Labels: Reviewing Internally, cla: yes

#167 Adding IntegrationFunction class. This represents an under-constructi…
  xls/contrib/integrator/BUILD
  xls/contrib/integrator/ir_integrator.cc
  xls/contrib/integrator/ir_integrator.h
  xls/contrib/integrator/ir_integrator_test.cc
Labels: Reviewing Internally, cla: yes
